#!/usr/bin/env bash
# Deploy on the VPS. SETTINGS ARE NEVER OVERWRITTEN: existing .env values are kept and
# only NEW keys from .env.example are appended; *.example configs are seeded once.
# (The caller fetch+reset's the code first; runtime config must be gitignored — see README.)
# Generated by ACE.
set -euo pipefail
cd "$(dirname "$0")/.."

# 1) merge new settings keys without clobbering live values
bash scripts/env-merge.sh .env.example .env

# 2) seed any *.example config that doesn't exist yet (never overwrite an existing one)
for ex in $(git ls-files '*.example' 2>/dev/null); do
  [ "$ex" = ".env.example" ] && continue
  target="${ex%.example}"
  [ -e "$target" ] || { cp "$ex" "$target"; echo "[deploy] seeded $target from $ex"; }
done

# 3) build + (re)start
IMAGE="localhost/app:latest"
echo "[deploy] building $IMAGE …"
podman build --target build -t "$IMAGE" -f Containerfile .
podman rm -f app 2>/dev/null || true
# EDIT: set the real run command + published port, e.g.:
# podman run -d --name app --restart=always --env-file .env -p 3000:3000 "$IMAGE" <start-cmd>
echo "[deploy] image built; set the run line to serve app."
