#!/usr/bin/env bash
# Deploy on the VPS. SETTINGS ARE NEVER OVERWRITTEN: existing .env values are kept and
# only NEW keys from .env.example are appended; *.example configs are seeded once.
# (The caller fetch+reset's the code first; runtime config must be gitignored — see README.)
# Generated by ACE.
set -euo pipefail
cd "$(dirname "$0")/.."

# 1) merge new settings keys without clobbering live values
bash scripts/env-merge.sh .env.example .env

# 2) seed any *.example config that doesn't exist yet (never overwrite an existing one)
for ex in $(git ls-files '*.example' 2>/dev/null); do
  [ "$ex" = ".env.example" ] && continue
  target="${ex%.example}"
  [ -e "$target" ] || { cp "$ex" "$target"; echo "[deploy] seeded $target from $ex"; }
done

# 3) build the runtime (final) image and (re)start the service.
# The start command lives in the Containerfile's `final` stage (CMD) — set it there for your app.
IMAGE="localhost/app:latest"
echo "[deploy] building $IMAGE (final image) …"
podman build --target final -t "$IMAGE" -f Containerfile .
podman rm -f app 2>/dev/null || true
podman run -d --name app --restart=always --env-file .env -p 3000:3000 "$IMAGE"
echo "[deploy] app running on :3000 (set the final-stage CMD if it is not up yet)"
